apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: service-layer

resources:
  - namespace.yaml
  - configmap.yaml
  - gateway-deployment.yaml
  - services-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: service-layer
  app.kubernetes.io/managed-by: kustomize
